import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-100 h-screen flex flex-col justify-center items-center ">
        <h1 className="text-3xl">Bug Free System</h1>
        <a
          href="https://shuvrosarkar.com"
          className="bg-slate-700 text-gray-200 mt-4 px-4 py-1 rounded"
        >
          By Shuvro Sarkar
        </a>
      </div>
    </>
  );
};

export default Home;
