import axios from 'axios';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Video } from '../../types/types';
import Feed from '../components/Layout/Feed';

interface IHome {
  videos: Video[];
}

const Home: NextPage<IHome> = ({ videos }) => {
  // videos = [];
  return (
    <>
      <Head>
        <title>TikTok - Set The Trend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Feed videos={videos} />
    </>
  );
};

export default Home;

export const getServerSideProps = async () => {
  const { data } = await axios.get('http://localhost:3000/api/post');
  return {
    props: {
      videos: data.videos,
    },
  };
};
