import type { NextPage } from 'next';
import Head from 'next/head';
import LoginForm from '../components/LoginForm';

const Login: NextPage = () => {
  return (
    <>
      <Head>
        <title>Videoxen - Set The Trend</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginForm />
    </>
  );
};

export default Login;
